require("set")
require("lazy-config")
require("hop-config")
require("bufferline-conf")
require("lualine-conf")
require("tree-conf")
require("alpha-config")
require("telescope-conf")
require "whichkey"
require("treesitter-conf")
require("coc-conf")
